Funcionalidad "Cambio de contraseña" funcional.
AnimatiWA/AnimatiApp pull request #120
Opened 2024-11-05 22:04 UTC by emir-argcoder

Se da continuidad al procedimiento desde vista Profile: 
![AnimatiApp Android – RecoveryPasswordActivity java  AnimatiApp_Android app main  5_11_2024 18_45_51](https://github.com/user-attachments/assets/8a111733-3983-4d74-86f3-a7622a35cd1d)

Se presenta la vista de recuperación de password completa:
![AnimatiApp Android – RecoveryPasswordActivity java  AnimatiApp_Android app main  5_11_2024 18_46_03](https://github.com/user-attachments/assets/8e199b12-b3ee-4cb5-9581-11f85a3924b3)

Valida si la contraseña cumple los requisitos de seguridad:
![AnimatiApp Android – RecoveryPasswordActivity java  AnimatiApp_Android app main  5_11_2024 18_46_47](https://github.com/user-attachments/assets/4fb2bd05-73cc-4c8c-af27-15c1854b17da)

Valida que ambas coincidan:
![AnimatiApp Android – RecoveryPasswordActivity java  AnimatiApp_Android app main  5_11_2024 18_46_25](https://github.com/user-attachments/assets/c30a7fc6-bb24-4673-ae02-8eaeb0edfa0a)

Si todo es correcto, notifica y en el próximo ingreso se debe autenticar con las nuevas credenciales:
![AnimatiApp Android – RecoveryPasswordActivity java  AnimatiApp_Android app main  5_11_2024 18_47_24](https://github.com/user-attachments/assets/32900be6-5e0c-4d3e-880f-d4895b56a1e8)

2024-11-05 22:10 UTC, emir-argcoder commented
A la versión final se le cambió la leyenda "Recuperar contraseña" a "Cambiar contraseña". 
- Puede que la vista de perfil tenga poca funcionalidad, posee botones (ocultos) para cambiar el mail y hacer seguimiento de la compra realizada.

2024-11-06 00:03 UTC, RochettiUriel requested changes

2024-11-06 00:03 UTC, RochettiUriel commented on AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
> +    permission_classes = [permissions.AllowAny]
Aca tiene que ir permissions.IsAuthenticated. Sino no sirve de nada pasarle Token.

2024-11-06 00:28 UTC, emir-argcoder commented on AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
> +    permission_classes = [permissions.AllowAny]
Modificación realizada.

2024-11-06 01:02 UTC, RochettiUriel approved these changes

2024-11-06 01:02 UTC, merged