ForgotPassword
AnimatiWA/AnimatiApp pull request #70
Opened 2024-10-23 05:16 UTC by emir-argcoder

Lógica y endpoint para envío de correos de recuperación.

2024-10-23 11:04 UTC, RochettiUriel requested changes
Hay un par de errores. Los dejo comentados con detalle. Principalmente se llama a un endpoint equivocado en el perfil de usuario y hay que modificar la vista que maneja la recuperacion de contraseña para que se ajuste a los estandares de las demas vistas.

2024-10-23 11:04 UTC, RochettiUriel commented on AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
Aca password_recovery esta creado como una función. Hay que crearlo como una clase al igual que las demás vistas para que funcione correctamente con DJango y se apliquen los controles de seguridad establecidos (control de permisos entre otras cosas). Despues preguntame cualquier cosa y te ayudo a hacer un endpoint generico para esto. O esperame y lo hago yo directamente.

2024-10-24 00:12 UTC, emir-argcoder commented
Modificaciones añadidas según revisión del colega.

2024-10-24 00:34 UTC, RochettiUriel approved these changes
Mando correcciones para un par de detallitos.

2024-10-24 00:35 UTC, merged